name: test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: ack
        run: echo "start building"
      - name: build docker container
        run: docker build -t self-healing-service . && docker run --name container-1 self-healing-service
